# Generated by Django 2.2.5 on 2019-09-22 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='muerte',
            field=models.DateField(blank=True, null=True, verbose_name='Fallecimiento'),
        ),
    ]
